"""IR → Python source string builder."""

from __future__ import annotations

from datetime import datetime, timezone

from shikoko.codegen.ir import EnumIR, QueryIR, ReturnKind

_INDENT = "    "


def render_module(
    queries: list[QueryIR],
    source_label: str,
    *,
    source_hash: str | None = None,
) -> str:
    """Generate a complete Python module from a list of :class:`QueryIR`.

    Render order is fixed for stable output: header → imports → enums
    (alphabetical) → row models (alphabetical) → query functions
    (alphabetical). The ``check`` subcommand relies on byte-stable
    generation.

    When *source_hash* is provided, a ``# hash:`` line is embedded in the
    header so the ``check`` subcommand can short-circuit when sources have
    not changed.
    """
    parts: list[str] = []

    # --- Header comment -------------------------------------------------------
    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    parts.append("# AUTO-GENERATED by shikoko — do not edit manually.")
    parts.append(f"# source: {source_label}")
    parts.append(f"# generated at: {ts}")
    if source_hash is not None:
        parts.append(f"# hash: {source_hash}")
    parts.append("")

    # --- Collect what we need to emit ----------------------------------------
    enums = _collect_enums(queries)

    # --- Imports --------------------------------------------------------------
    # NOTE: intentionally omit ``from __future__ import annotations``.
    # PEP 604 union syntax (``int | None``) is available at runtime in
    # Python 3.10+, which is our minimum. Skipping the future import lets
    # Pydantic v2 resolve field annotations without a manual
    # ``model_rebuild()`` step in dynamically-loaded modules.

    extra_imports: set[str] = set()
    for q in queries:
        for p in q.params:
            extra_imports.update(p.py_type.imports)
        for f in q.fields:
            extra_imports.update(f.py_type.imports)

    parts.append("import asyncpg")
    for imp in sorted(extra_imports):
        parts.append(imp)

    has_row_models = any(q.return_kind != ReturnKind.EXEC and q.fields for q in queries)
    if has_row_models:
        parts.append("from pydantic import BaseModel, ConfigDict")

    if enums:
        parts.append("from enum import StrEnum")
    parts.append("")

    # --- Enums (alphabetical by Python class name) ---------------------------
    for enum_ir in enums:
        _render_enum(parts, enum_ir)
        parts.append("")

    # --- Per-query content ---------------------------------------------------
    sorted_queries = sorted(queries, key=lambda q: q.name)
    for i, q in enumerate(sorted_queries):
        if i > 0:
            parts.append("")
            parts.append("")

        # SQL constant.
        const_name = f"_{q.name.upper()}_SQL"
        parts.append(f'{const_name} = """')
        parts.append(q.sql)
        parts.append('"""')
        parts.append("")

        # Row model class (skip for EXEC).
        if q.return_kind != ReturnKind.EXEC and q.fields:
            parts.append(f"class {q.row_model_name}(BaseModel):")
            if q.doc:
                parts.append(f'{_INDENT}"""{q.doc}"""')
            parts.append(
                f"{_INDENT}model_config = ConfigDict(frozen=True, extra='forbid')"
            )
            parts.append("")
            for field in q.fields:
                annotation = field.py_type.annotation
                if field.nullable:
                    parts.append(f"{_INDENT}{field.name}: {annotation} | None = None")
                else:
                    parts.append(f"{_INDENT}{field.name}: {annotation}")
            parts.append("")

        # Async function.
        _render_function(parts, q)

    parts.append("")  # trailing newline
    return "\n".join(parts)


def _collect_enums(queries: list[QueryIR]) -> list[EnumIR]:
    """Return all distinct enums used across *queries*, sorted by Python name.

    Deduplicated by ``pg_name``: two queries referencing the same
    Postgres enum produce one Python class.
    """
    seen: dict[str, EnumIR] = {}
    for q in queries:
        for e in q.enums_used:
            seen.setdefault(e.pg_name, e)
    return sorted(seen.values(), key=lambda e: e.py_name)


def _render_enum(parts: list[str], enum_ir: EnumIR) -> None:
    parts.append(f"class {enum_ir.py_name}(StrEnum):")
    if not enum_ir.variants:
        parts.append(f"{_INDENT}pass")
        return
    for py_member, pg_label in enum_ir.variants:
        # repr() round-trips through Python literals correctly,
        # including quotes and escapes within the label.
        parts.append(f"{_INDENT}{py_member} = {pg_label!r}")


def _render_function(parts: list[str], q: QueryIR) -> None:
    """Append the async query function to *parts*."""
    # Signature.
    params_sig = ["conn: asyncpg.Connection"]
    for p in q.params:
        annotation = p.py_type.annotation
        if p.nullable:
            params_sig.append(f"{p.name}: {annotation} | None = None")
        else:
            params_sig.append(f"{p.name}: {annotation}")

    parts.append(f"async def {q.name}(")
    for sig in params_sig:
        parts.append(f"{_INDENT}{sig},")
    parts.append(f") -> {_return_type_annotation(q)}:")

    if q.doc:
        parts.append(f'{_INDENT}"""{q.doc}"""')

    const_name = f"_{q.name.upper()}_SQL"
    param_names = ", ".join(p.name for p in q.params)

    if q.return_kind == ReturnKind.EXEC:
        call = f"await conn.execute({const_name}"
        if param_names:
            call += f", {param_names}"
        call += ")"
        parts.append(f"{_INDENT}{call}")
        parts.append(f"{_INDENT}return None")
    elif q.return_kind == ReturnKind.ONE:
        parts.append(f"{_INDENT}_row = await conn.fetchrow({const_name}")
        if param_names:
            parts[-1] += f", {param_names}"
        parts[-1] += ")"
        parts.append(f"{_INDENT}if _row is None:")
        parts.append(f"{_INDENT * 2}return None")
        parts.append(f"{_INDENT}return {q.row_model_name}.model_validate(dict(_row))")
    else:
        parts.append(f"{_INDENT}_rows = await conn.fetch({const_name}")
        if param_names:
            parts[-1] += f", {param_names}"
        parts[-1] += ")"
        parts.append(
            f"{_INDENT}return [{q.row_model_name}.model_validate(dict(_r)) for _r in _rows]"
        )


def _return_type_annotation(q: QueryIR) -> str:
    """Return the Python return-type annotation string for *q*."""
    if q.return_kind == ReturnKind.EXEC:
        return "None"
    if q.return_kind == ReturnKind.ONE:
        return f"{q.row_model_name} | None"
    return f"list[{q.row_model_name}]"
