# AUTO-GENERATED by shikoko — do not edit manually.
# source: orders/sql
# generated at: 2026-05-19 23:48:40 UTC
# hash: 8caf44990859b06a93a5868b464fc3952f59a54cf134f214fa88144388d13c9e

import asyncpg
from datetime import datetime
from decimal import Decimal
from pydantic import BaseModel, ConfigDict
from enum import StrEnum


class OrderStatus(StrEnum):
    PENDING = "pending"
    CONFIRMED = "confirmed"
    SHIPPED = "shipped"
    DELIVERED = "delivered"
    CANCELLED = "cancelled"


class PaymentMethod(StrEnum):
    CREDIT_CARD = "credit_card"
    BANK_TRANSFER = "bank_transfer"
    CRYPTO = "crypto"


_LIST_ORDERS_BY_PAYMENT_SQL = """
select
  o.id,
  o.user_id,
  o.total,
  o.status,
  o.paid_with,
  o.created_at
from orders o
where o.user_id = $1
  and o.paid_with = $2::payment_method
order by o.created_at desc
"""


class ListOrdersByPaymentRow(BaseModel):
    """List orders for a user with a specific payment method."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: int | None = None
    user_id: int | None = None
    total: Decimal | None = None
    status: OrderStatus | None = None
    paid_with: PaymentMethod | None = None
    created_at: datetime | None = None


async def list_orders_by_payment(
    conn: asyncpg.Connection,
    _1: int | None = None,
    _2: PaymentMethod | None = None,
) -> list[ListOrdersByPaymentRow]:
    """List orders for a user with a specific payment method."""
    _rows = await conn.fetch(_LIST_ORDERS_BY_PAYMENT_SQL, _1, _2)
    return [ListOrdersByPaymentRow.model_validate(dict(_r)) for _r in _rows]


_LIST_ORDERS_BY_STATUS_SQL = """
select
  o.id,
  o.user_id,
  o.total,
  o.status,
  o.paid_with,
  o.created_at
from orders o
where o.status = $1::order_status
order by o.created_at desc
"""


class ListOrdersByStatusRow(BaseModel):
    """List orders filtered by status."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: int | None = None
    user_id: int | None = None
    total: Decimal | None = None
    status: OrderStatus | None = None
    paid_with: PaymentMethod | None = None
    created_at: datetime | None = None


async def list_orders_by_status(
    conn: asyncpg.Connection,
    _1: OrderStatus | None = None,
) -> list[ListOrdersByStatusRow]:
    """List orders filtered by status."""
    _rows = await conn.fetch(_LIST_ORDERS_BY_STATUS_SQL, _1)
    return [ListOrdersByStatusRow.model_validate(dict(_r)) for _r in _rows]


_UPDATE_ORDER_STATUS_SQL = """
update orders
set status = $2::order_status
where id = $1
returning id, user_id, total, status, paid_with, created_at
"""


class UpdateOrderStatusRow(BaseModel):
    """Change an order's status (e.g. confirm, ship, cancel)."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: int
    user_id: int
    total: Decimal
    status: OrderStatus
    paid_with: PaymentMethod | None = None
    created_at: datetime


async def update_order_status(
    conn: asyncpg.Connection,
    _1: int | None = None,
    _2: OrderStatus | None = None,
) -> UpdateOrderStatusRow | None:
    """Change an order's status (e.g. confirm, ship, cancel)."""
    _row = await conn.fetchrow(_UPDATE_ORDER_STATUS_SQL, _1, _2)
    if _row is None:
        return None
    return UpdateOrderStatusRow.model_validate(dict(_row))
