# AUTO-GENERATED by shikoko — do not edit manually.
# source: users/sql
# generated at: 2026-05-19 23:48:40 UTC
# hash: 0b6b4edda2ffe074c0398c430b546e2ebb67371335b657e17367dd4e39693fd3

import asyncpg
from datetime import datetime
from pydantic import BaseModel, ConfigDict

_CREATE_USER_SQL = """
insert into users (email, name, org_id)
values ($1, $2, $3)
returning id, email, name, org_id, created_at
"""


class CreateUserRow(BaseModel):
    """Insert a new user and return the generated row."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: int
    email: str
    name: str | None = None
    org_id: int | None = None
    created_at: datetime


async def create_user(
    conn: asyncpg.Connection,
    _1: str | None = None,
    _2: str | None = None,
    _3: int | None = None,
) -> CreateUserRow | None:
    """Insert a new user and return the generated row."""
    _row = await conn.fetchrow(_CREATE_USER_SQL, _1, _2, _3)
    if _row is None:
        return None
    return CreateUserRow.model_validate(dict(_row))


_DELETE_USER_SQL = """
delete from users
where id = $1
"""


async def delete_user(
    conn: asyncpg.Connection,
    _1: int | None = None,
) -> None:
    """Delete a user by id."""
    await conn.execute(_DELETE_USER_SQL, _1)
    return None


_FIND_USER_BY_EMAIL_SQL = """
select
  u.id,
  u.email,
  u.name,
  u.created_at,
  o.name as org_name
from users u
left join orgs o on o.id = u.org_id
where u.email = $1
"""


class FindUserByEmailRow(BaseModel):
    """Find a single user by email address.
    Returns None if the user does not exist."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: int
    email: str
    name: str | None = None
    created_at: datetime
    org_name: str | None = None


async def find_user_by_email(
    conn: asyncpg.Connection,
    _1: str | None = None,
) -> FindUserByEmailRow | None:
    """Find a single user by email address.
    Returns None if the user does not exist."""
    _row = await conn.fetchrow(_FIND_USER_BY_EMAIL_SQL, _1)
    if _row is None:
        return None
    return FindUserByEmailRow.model_validate(dict(_row))


_LIST_POSTS_BY_USER_SQL = """
select
  p.id,
  p.title,
  p.body,
  p.created_at
from posts p
where p.user_id = $1
order by p.created_at desc
"""


class ListPostsByUserRow(BaseModel):
    """List all posts by a given user, newest first."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: int
    title: str
    body: str | None = None
    created_at: datetime


async def list_posts_by_user(
    conn: asyncpg.Connection,
    _1: int | None = None,
) -> list[ListPostsByUserRow]:
    """List all posts by a given user, newest first."""
    _rows = await conn.fetch(_LIST_POSTS_BY_USER_SQL, _1)
    return [ListPostsByUserRow.model_validate(dict(_r)) for _r in _rows]


_LIST_USERS_SQL = """
select
  u.id,
  u.email,
  u.name,
  o.name as org_name
from users u
left join orgs o on o.id = u.org_id
order by u.id
"""


class ListUsersRow(BaseModel):
    """List all users with their org name.
    Left join ensures users without an org are still included."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: int
    email: str
    name: str | None = None
    org_name: str | None = None


async def list_users(
    conn: asyncpg.Connection,
) -> list[ListUsersRow]:
    """List all users with their org name.
    Left join ensures users without an org are still included."""
    _rows = await conn.fetch(_LIST_USERS_SQL)
    return [ListUsersRow.model_validate(dict(_r)) for _r in _rows]
