"""Unit tests for the ``check`` module."""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from pysquirrel.check import (
    CheckResult,
    compute_source_hash,
    extract_hash_from_generated,
)


class TestComputeSourceHash:
    def test_deterministic(self, tmp_path: Path) -> None:
        f1 = tmp_path / "a.sql"
        f2 = tmp_path / "b.sql"
        f1.write_text("select 1", encoding="utf-8")
        f2.write_text("select 2", encoding="utf-8")

        h1 = compute_source_hash([f1, f2])
        h2 = compute_source_hash([f1, f2])
        assert h1 == h2
        assert len(h1) == 64  # SHA-256 hex digest

    def test_order_independent(self, tmp_path: Path) -> None:
        """Hash is order-independent because files are sorted internally."""
        f1 = tmp_path / "a.sql"
        f2 = tmp_path / "b.sql"
        f1.write_text("select 1", encoding="utf-8")
        f2.write_text("select 2", encoding="utf-8")

        h1 = compute_source_hash([f1, f2])
        h2 = compute_source_hash([f2, f1])
        assert h1 == h2

    def test_content_matters(self, tmp_path: Path) -> None:
        f1 = tmp_path / "a.sql"
        f1.write_text("select 1", encoding="utf-8")

        h1 = compute_source_hash([f1])

        f1.write_text("select 2", encoding="utf-8")
        h2 = compute_source_hash([f1])
        assert h1 != h2

    def test_empty_list(self) -> None:
        h = compute_source_hash([])
        assert h == hashlib.sha256(b"").hexdigest()


class TestExtractHashFromGenerated:
    def test_extracts_hash(self) -> None:
        source = (
            "# AUTO-GENERATED by pysquirrel — do not edit manually.\n"
            "# source: sql\n"
            "# generated at: 2025-01-01 00:00:00 UTC\n"
            "# hash: abc123\n"
            "\n"
            "import asyncpg\n"
        )
        assert extract_hash_from_generated(source) == "abc123"

    def test_returns_none_when_missing(self) -> None:
        source = (
            "# AUTO-GENERATED by pysquirrel — do not edit manually.\n"
            "# source: sql\n"
            "# generated at: 2025-01-01 00:00:00 UTC\n"
            "\n"
            "import asyncpg\n"
        )
        assert extract_hash_from_generated(source) is None

    def test_stops_at_code_line(self) -> None:
        """Stops scanning when a non-comment, non-blank line is reached."""
        source = (
            "# AUTO-GENERATED by pysquirrel — do not edit manually.\n"
            "import asyncpg\n"
            "# hash: should_not_be_found\n"
        )
        assert extract_hash_from_generated(source) is None

    def test_finds_hash_after_blank_line(self) -> None:
        """Blank lines within the header don't stop the scan."""
        source = (
            "# AUTO-GENERATED by pysquirrel — do not edit manually.\n\n# hash: abc\n"
        )
        assert extract_hash_from_generated(source) == "abc"

    def test_whitespace_around_hash(self) -> None:
        source = "#   hash:   deadbeef  \n"
        assert extract_hash_from_generated(source) == "deadbeef"


class TestCheckResult:
    def test_matches_when_empty(self) -> None:
        result = CheckResult(matches=True)
        assert result.matches is True
        assert result.diffs == {}
        assert result.missing == []
        assert result.stale == []

    def test_no_matches_with_diffs(self) -> None:
        result = CheckResult(
            matches=False,
            diffs={Path("x.py"): "--- x\n+++ x\n"},
        )
        assert result.matches is False
